### ISSUE TITLE
Triggering the control doesn't work on iOS12

### ISSUE THREAD

**Issue by alexppmax** [takecian/SwiftRater#10]
Hey, first of all thank you for your work.

We implemented your class into our project and it works just fine for iOS10 and iOS11, but on the latest iOS12 beta the control is not shown when trying to access it (we implemented it when user taps a link).

Are you aware of this issue? Is there anything that I can help you with to fix this and be prepared for when iOS12 is coming out? 

Thanks,
Alex.

**Comment by takecian** [comment]
Hi Alex, thanks for telling this.
I'm not aware this. Which API does not work?
I'd like to check and fix it before iOS 12 release.

**Comment by takecian** [comment]
I have tried with iOS12 simulator and call `rateApp()`, it has shown popup.
@alex-strafalogea ,  could you elaborate your environment?

**Comment by takecian** [comment]
I have confirmed this works on iOS12.
If you find issues, please reopen.
