### ISSUE TITLE
App Store Connect Operation Error Invalid Bundle. The bundle at 'BalGuide.app/Frameworks/SwiftRater.framework' contains disallowed file 'Frameworks'.

### ISSUE THREAD

**Issue by JulesMoorhouse** [takecian/SwiftRater#20]
I'm getting the following error when I upload to the app store

App Store Connect Operation Error Invalid Bundle. The bundle at 'BalGuide.app/Frameworks/SwiftRater.framework' contains disallowed file 'Frameworks'.

**Comment by takecian** [comment]
How do you integrate SwiftRater? I need more detailed information.

**Comment by JulesMoorhouse** [comment]
Cocoapods and I’m using the latest version of SwiftRater. Also the latest release version of Xcode. And using Objective C

**Comment by JulesMoorhouse** [comment]
This fixed the issue for me...

https://stackoverflow.com/a/35591792/450456
