### ISSUE TITLE
The Submit Button Not Works, it's gray

### ISSUE THREAD

**Issue by FlashTang** [takecian/SwiftRater#24]
The submit button not Works, it's gray, can not click
Xcode 10 , swift 4.2 , real device and simulator all the same.
How can I fix it ?
Thank you

**Comment by takecian** [comment]
What is submit button? Please tell me details.

**Comment by FlashTang** [comment]
Thanks for the quick reply
submit button is the button appears on the right bottom  side after tapping stars (when SwiftRater.useStoreKitIfAvailable = true )
 is the "送信" button in Japanese

**Comment by takecian** [comment]
Could you share screenshot of that? It seems UI of StoreKit.

**Comment by FlashTang** [comment]
![img_0640](https://user-images.githubusercontent.com/920751/51074155-87388d00-16b6-11e9-8035-708f1c44867c.jpg)

Hello takecian , here is the screenshoot , as you can see the submit button is grayout ， disenabled

**Comment by takecian** [comment]
See this, https://stackoverflow.com/questions/45057452/why-the-skstorereviewcontroller-does-not-let-me-submit-a-review

**Comment by FlashTang** [comment]
Seems it's not SwiftRater issue , thanks for the link and your help

**Comment by takecian** [comment]
No problem~ :)
