### ISSUE TITLE
Rate pop up appears on every app launch

### ISSUE THREAD

**Issue by PretzelJones** [takecian/SwiftRater#25]
No matter what I set in appdelegate the rate popup appears on every app launch. This occurs in the simulator and on a physical device.

**Comment by takecian** [comment]
Could you share that code?

**Comment by PretzelJones** [comment]
I think the main issue is that there is no way for the user to not leave a review but also not be bothered by the popup. So if I don't leave a review, the only option I have have is "Not now" which just prompts the user on every app launch.

But here is the code from my appdelegate.swift file. I installed vie cocoapods.

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        SwiftRater.daysUntilPrompt = 1
        SwiftRater.usesUntilPrompt = 2
        SwiftRater.significantUsesUntilPrompt = 3
        SwiftRater.daysBeforeReminding = 1
        SwiftRater.showLaterButton = true
        SwiftRater.debugMode = true
        SwiftRater.appLaunched()
        //firebase functionality
        FirebaseApp.configure()
        return true
    }

**Comment by takecian** [comment]
Did you call `SwiftRater.check()`?

**Comment by PretzelJones** [comment]
That might be what I'm missing. I'll give that a try. Thank you.
