### ISSUE TITLE
Error retrieving App Store data as an error was returned.

### ISSUE THREAD

**Issue by hamza-mansouur** [takecian/SwiftRater#27]
Hello I am trying to run the demo project but I got this error: Error retrieving App Store data as an error was returned.

**Comment by takecian** [comment]
SwiftRater gets app version information from appstore. Please replace bundle id with your app.

**Comment by hamza-mansouur** [comment]
Hey Tekecian, thank you for your reply, so the app will not show the stars unless it's on app store ?
even with testflight it doesn't work.

**Comment by takecian** [comment]
Could you call api directly `http://itunes.apple.com/lookup?bundleId={YOUR_APP_BUNDLE_ID}` ?
e.g.: http://itunes.apple.com/lookup?bundleId=com.takecian.cospa

SwiftRater uses response of that api.

**Comment by takecian** [comment]
If you have more question about this, please reopen this.
