### ISSUE TITLE
Submit button hook up 

### ISSUE THREAD

**Issue by karmsingh** [takecian/SwiftRater#28]
Hi there, first nice job on making this pure swift...much easier and lightweight vs. Armchair.

Please can you fully detail and explain how we get the action implemented for the **submit button** please? For example it is greyed out and disabled. The current explanation and documentation for how to have this submit direct to App Store is not complete.

Appreciated

**Comment by takecian** [comment]
Hi @karmsingh ,
Could you elaborate `Submit button`? It would be help to understand if you attach screenshot.

Thanks.

**Comment by karmsingh** [comment]
![IMG_6144](https://user-images.githubusercontent.com/2523151/63974647-1afe7400-ca62-11e9-9467-cd7d8deb5937.PNG)

**Comment by takecian** [comment]
Thanks, it is because submit button is available on store app.

This would be help, https://stackoverflow.com/questions/45057452/why-the-skstorereviewcontroller-does-not-let-me-submit-a-review

**Comment by takecian** [comment]
If you have more question about this, please reopen this.
