### ISSUE TITLE
iTunes lookup api returns empty list

### ISSUE THREAD

**Issue by NameX44** [takecian/SwiftRater#30]
Hi,

The iTunes lookup api returns empty list. If I try to add country code in url then it works. My bundle Id is good.

Doesn't work : https://itunes.apple.com/lookup?bundleId=xxxxx
works : https://itunes.apple.com/fr/lookup?bundleId=xxxxx

Any idea about that ?

Thanks

**Comment by takecian** [comment]
Hmm, I tried it with my app, it worked without country code.

https://itunes.apple.com/lookup?bundleId=com.cocomoe.carp

I need some time to investigate.

**Comment by NameX44** [comment]
Is your app available in every countries ? Mine is available in Europe only.

**Comment by takecian** [comment]
I have updated https://github.com/takecian/SwiftRater/commit/391c780a285573ab58ac342be255a61c1baeac9f and published `1.7.0`. You can set country code,

```
SwiftRater.countryCode = "fr"
```

https://github.com/takecian/SwiftRater#country-code

Could you try this?

**Comment by NameX44** [comment]
Hi, thanks for your fast response.

What if I support multi country but only en/fr store page ?

Why don't you use fetching from app id ?

Thanks,

**Comment by takecian** [comment]
Although it requires developers extra effort,  I have added this feature.
https://github.com/takecian/SwiftRater#app-id

You can try this with `1.8.0`.
Thanks.
