### ISSUE TITLE
Localization doesn't work if SwiftRater installed using SwiftPM

### ISSUE THREAD

**Issue by wacumov** [takecian/SwiftRater#34]
Hello. If the library is installed via SwiftPM then localization does not work. 
This is not big issue when speaking about 3 of 4 keys from `SwiftRaterLocalization` table, because these keys are normal English strings. But "Rater.title" is not, so the alert message looks bad.

**Comment by takecian** [comment]
Thank you for sending PR.
I've released it as 1.9.1.

**Comment by wacumov** [comment]
That's great!
Thank you for the library.
