### ISSUE TITLE
Significant event trigger 

### ISSUE THREAD

**Issue by JulesMoorhouse** [takecian/SwiftRater#4]
Hi

Does this framework fallback to the new iOS 10 rating api / rules? Awesome I see that it does.

Does it support uialertcontroller?

Also when say 5 significant events occur, can the rating dialog be shown instantly regardless of days or uses ?

Thanks

Jules.

**Comment by takecian** [comment]
>Does this framework fallback to the new iOS 10 rating api / rules? Awesome I see that it does.

SwiftRater supports new rating api [here](https://github.com/takecian/SwiftRater/blob/master/SwiftRater/SwiftRater.swift#L280).

>Does it support uialertcontroller?

What does it mean?
SwiftRater uses uialertcontroller for devices which are iOS10.2 or below.

>Also when say 5 significant events occur, can the rating dialog be shown instantly regardless of days or uses ?

Yes. SwiftRater tries to show rating dialog when one of conditions you set meets.

**Comment by JulesMoorhouse** [comment]
Awesome, that sounds great. 

Thanks for your quick reply.

I will have to look into bridging headers for objective c 🤔

**Comment by takecian** [comment]
As of now SwiftRater is written in Swift and is not able to be used from objective-c as these classes don't have `@objc` attribute.
Wait a 10 minutes to modify to add `@objc` attribute.

**Comment by takecian** [comment]
I added `@objc` to `SwiftRater` class so you can use it from objc.
Please try it out with ver `0.2.0`.

**Comment by JulesMoorhouse** [comment]
Oh ok thanks.

I haven't tried adding a swift cocopod before.

What do I need to do? I've heard I would need to create a bridging header?

Thanks again.

**Comment by takecian** [comment]
Bridging header is needed if you call Objc code from Swift code.
Bridging header is not needed if you call Swift code from Objc code.

You just need to add `SwiftRater` into Podfile as follows.

```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'YOUR_TARGET' do
  pod 'SwiftRater'
end
```

**Comment by JulesMoorhouse** [comment]
Thanks,

How do I call SwiftRater in Objective C, I've added my import and that doesn't cause an error.
`#import <SwiftRater/SwiftRater.h>`

I'm using cocoapods and using `use_frameworks!`

I've tried the swift code with a semicolon, which I didn't expect to work.

I've also tried
`[[SwiftRater sharedInstance] incrementSignificantUsageCount];`

Not sure what else to try ?

**Comment by takecian** [comment]
Try this out,

AppDelegate.m
```
#import "AppDelegate.h"
#import <SwiftRater/SwiftRater-Swift.h>

@interface AppDelegate ()

@end

@implementation AppDelegate


- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    // Override point for customization after application launch.

    SwiftRater.significantUsesUntilPrompt = 3;
    [SwiftRater appLaunched];
    return YES;
}
...

```

ViewController.m
```
#import "ViewController.h"
#import <SwiftRater/SwiftRater-Swift.h>

@interface ViewController ()

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.
    [SwiftRater check];
}


- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

```

**Comment by JulesMoorhouse** [comment]
Sorry for another question.

With debug mode enabled check does fire the rating dialog.

However I've called the significant method more than the significant uses prompt amount and check didn't then fire the rating dialog.

I'm calling check in `viewWillAppear`.

Here's my setup.

<img width="322" alt="skitch 10" src="https://user-images.githubusercontent.com/361024/27374047-52b13570-5662-11e7-9238-a68be330e661.png">

**Comment by takecian** [comment]
If debug mode enabled, rating dialog popup every time. see [logic](https://github.com/takecian/SwiftRater/blob/master/SwiftRater/UsageDataManager.swift#L113).
If rating dialog shown once, dialog is not shown even if another condition met, as SwiftRater prevent from showing popup too much times. see [logic](https://github.com/takecian/SwiftRater/blob/master/SwiftRater/UsageDataManager.swift#L117).

**Comment by JulesMoorhouse** [comment]
Ah ok.

I tried remind me later and then left the screen and returned to it, the rating dialog then appeared.
I have daysBeforeReminding set to 1.

**Comment by JulesMoorhouse** [comment]
It would also be perfect if I could override my application name, as I use a much shorter version for that shown on the home screen.

**Comment by takecian** [comment]
See [README](https://github.com/takecian/SwiftRater#customize-text)

**Comment by JulesMoorhouse** [comment]
So daysBeforeReminding  is working as expected, surely that should wait regardless of other settings?

**Comment by takecian** [comment]
Oh, I found issue. I will fix it.

**Comment by takecian** [comment]
I found issue related reminder, i fixed it.
Try it out with `0.2.1`.

Thank you!

**Comment by JulesMoorhouse** [comment]
I'm just about done, however the submit button on the review api dialog isn't working.
The submit text is in grey and can not be tapped.

I thought it might be a network issue but that doesn't appear to be the case.

Please advise.

Thanks.

**Comment by takecian** [comment]
Please attach screenshot. I need more details.

**Comment by JulesMoorhouse** [comment]
![img_4938](https://user-images.githubusercontent.com/361024/27391878-01ef11bc-569d-11e7-889f-9af1e4244ef1.JPG)

**Comment by JulesMoorhouse** [comment]
Ahhh https://stackoverflow.com/questions/43068925/skstorereviewcontroller-requestreview-doesnt-prompt-for-review

**Comment by JulesMoorhouse** [comment]
I'm a little concerned.
I had my device plugged in and ran from Xcode and the Rating dialog was showing.
Now I'm using a testflight version it's not :(, I'm using the latest release of iOS (Not Beta)

**Comment by JulesMoorhouse** [comment]
OK so while using a testflight build I've tested on....

iOS 10.3.2 - this didn't show a dialog after the significant count was reached or when I use my write a review button.
iOS 10.3.1 - the same results.
iOS 9 - the old style rating was used correctly in both cases.

http://www.developerinsider.in/skstorereviewcontroller-allow-users-to-provide-ratings-from-within-your-ios-app/

Looking at the bottom paragraph in the post above, this is the expected behaviour.

Nonetheless, it would be nice if there was some sort of failure condition provided by `SKStoreReviewController` so it was possible to determine that the code was working.

**Comment by takecian** [comment]
What we can do is to call [requestReview()](https://developer.apple.com/documentation/storekit/skstorereviewcontroller/2851536-requestreview) when condition has been met.

This method is void function, so we cannot know whether it succeeded or not.
I have just added `NSLog` when trying to show popup for ver `0.2.2`.
https://github.com/takecian/SwiftRater/commit/f85f1a1e1d5883758ec52350c1e2b6c449279c05
You could check terminal log.

**Comment by JulesMoorhouse** [comment]
I've submitted my app review. I'm confident it will work.

Cheers.
