### ISSUE TITLE
adding a variable in SwiftRater.swift

### ISSUE THREAD

**Issue by Cmk427** [takecian/SwiftRater#45]
It that suitable to add a variable which may call "isMetConditions" to check is it meet the conditions?
It maybe just like:
    @objc public static var  isMetConditions : Bool = UsageDataManager.shared.ratingConditionsHaveBeenMet

Therefore, i can add a view to ask user whether you like the app if the user meet the rating conditions. If yes, do .check(). 
Thank you

**Comment by takecian** [comment]
Hi, I'd appreciate it if you can make a PR for this.
I don't have the bandwidth for that.

**Comment by takecian** [comment]
Added this and this is in 2.1.1.
https://github.com/takecian/SwiftRater/commit/7b0bf6daf94b1827f1dbb91060fb6f736becd84d
