### ISSUE TITLE
'keyWindow' was deprecated in iOS 13.0

### ISSUE THREAD

**Issue by JulesMoorhouse** [takecian/SwiftRater#46]
Hi,

There's a warning when the minimum deployment version is iO14.

> 'keyWindow' was deprecated in iOS 13.0: Should not be used for applications that support multiple scenes as it returns a key window across all connected scenes

Also...

> 'requestReview()' was deprecated in iOS 14.0

FYI - I'm also using in an Obj C project...

**Comment by takecian** [comment]
Thanks for the heads up.
I will take a look when I have bandwidth.

**Comment by fabien79** [comment]
Hello, did you had time to check ?
I've got the same warnings on my side.
Thanks for your help

**Comment by takecian** [comment]
Resolved warnings.
https://github.com/takecian/SwiftRater/commit/f372c7c82bbe5e00d062ae2c0dccd5b26ada7176
