### ISSUE TITLE
Feature Request: App title parameter

### ISSUE THREAD

**Issue by JulesMoorhouse** [takecian/SwiftRater#5]
Hi

I would like request an app title parameter.

I know you can change all the strings, but then you loose the benefit of the localizations.

I would you also use this in my other apps next update.

PS. Once live the issues I had about the 10.3 api seemed fine.

Good job!

**Comment by takecian** [comment]
How about using `NSLocalizedString` to set strings?
```
SwiftRater.alertTitle = NSLocalizedString("alertTitle", comment: "")
```

**Comment by JulesMoorhouse** [comment]
Yes but that's replacing the whole string, you've already localized the wording around the app name.

**Comment by takecian** [comment]
You can reuse SwiftRater's localized strings by copying `SwiftRaterLocalization.strings` into your project and modify content of your `SwiftRaterLocalization.strings`.

**Comment by JulesMoorhouse** [comment]
I'm not sure why your reluctant to provide such a simple to change, I've seen this done in iRate etc.

In my case my home screen app name is 'Bal Guide' but I'd like to use my full app name 'Balance Guide'. Surely a simple property to override the bundle name to use an appName property would be an easy change?

**Comment by JulesMoorhouse** [comment]
Sorry I'm actually talking about alertMessage, I don't mean the alertTitle property by the app name.

**Comment by takecian** [comment]
Actually I'm not sure what you want. 

- You want modify app name used at localization
- You want modify alertMessage

Which?

**Comment by JulesMoorhouse** [comment]
I want to be able to specify the app name used here %@ (see below) with a parameter, where not specified fall back to the default as-is now.

["Rater.title" = "If you enjoy using %@, would you mind taking a moment to rate it? It won't take more than a minute. Thanks for your support!";])

Rather than SwiftRater using the app name from my bundle.

Sorry to be so confusing.

**Comment by takecian** [comment]
Try `SwiftRater.appName = "your full app name"` with ver `0.2.3`.

**Comment by JulesMoorhouse** [comment]
Awesome, thanks 👍
