### ISSUE TITLE
Issue useing SwiftRater.check()

### ISSUE THREAD

**Issue by BhavinBhadani** [takecian/SwiftRater#8]
When I click on button to show RatingView, it logs me but nothing prompts

     [SwiftRater]  will check daysUntilPrompt
     [SwiftRater]  will check usesUntilPrompt

My code is

     SwiftRater.reset()
     DispatchQueue.main.async {
            SwiftRater.check()
      }

**Comment by BhavinBhadani** [comment]
Ok now it works as reset creates an issue but now If I select not now then it logs

      [SwiftRater]  Already rated

And not prompt rating view another time. Any solution to show rating view every time on button selected?

**Comment by takecian** [comment]
@BhavinBhadani could you try the latest version `1.1.0`?

**Comment by BhavinBhadani** [comment]
ok let me check

**Comment by BhavinBhadani** [comment]
I got an error now. I do clean code and run the code and even reinstall it.

            dyld: Library not loaded: @rpath/SwiftRater.framework/SwiftRater
            Reason: no suitable image found.  Did find:

**Comment by BhavinBhadani** [comment]
ok done. The issue was with a pod. First I completely remove it and reinstall it. And it works. But the problem remains same. If I clicked not now and check again on click of rating, it doesn't show any dialogue and give a log 

    [SwiftRater]  Already rated

**Comment by takecian** [comment]
Oh, I understood what you pointed.
Which iOS version are you using?
If iOS 10.3 or later, the library cannot know which item users selected after showing dialog.

**Comment by BhavinBhadani** [comment]
ok So how do we know that rating is done or not?

**Comment by takecian** [comment]
There is no way to know it.

If you'd always like to show rating popup, please use this instead of `check()`
```
SwiftRater.rateApp()
```

**Comment by BhavinBhadani** [comment]
Ok thanks

**Comment by BhavinBhadani** [comment]
@takecian but some serious problem with swiftrater pod as error comes after reinstall and we need to reinstall pods for that

        dyld: Library not loaded: @rpath/SwiftRater.framework/SwiftRater
        Reason: no suitable image found.  Did find:
