### ISSUE TITLE
Issue with swiftrater pods

### ISSUE THREAD

**Issue by BhavinBhadani** [takecian/SwiftRater#9]
I am trying to update swiftrater pod but it gives me an error

    dyld: Library not loaded: @rpath/SwiftRater.framework/SwiftRater
    Reason: no suitable image found.  Did find:

So, to solve this I need to remove pod and reinstall it and then it works. Should be some work through here.

**Comment by takecian** [comment]
please reopen if the latest version does not work. 
Thank you.
